services:
  db:
    image: cockroachdb/cockroach:latest
    container_name: my_cockroach
    restart: always
    environment:
      COCKROACH_HOST: localhost
      COCKROACH_PORT: 26258
      COCKROACH_USER: myuser
      COCKROACH_PASSWORD: mypassword
      COCKROACH_DATABASE: mydatabase
    command: start-single-node --accept-sql-without-tls --http-addr=:8081
    ports:
      - "5432:26257"
      - "8081:8081" # CockroachDB Admin UI
    volumes:
      - cockroach_data:/cockroach/cockroach-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  cockroach_data:
